### ISSUE TITLE
bug: handle does not show before first click

### ISSUE THREAD

**Issue by juliasophieg** [sirisayshello/recipe-declutter#239]
When reordering ingredients and instructions, the handle does not show initially, but it still works. After the first click it shows correctly.

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the EditIngredientsList component to ensure the drag handle (IconMenu) is always visible by moving it outside the Menu component.

You can review changes in this commit: https://github.com/lattaai12/sirisayshello-recipe-declutter-239/commit/8c2d912e409462c64ffb55bbaaddc187a996372d.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
